

services:
  gemini-image:
    build: .
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    # For development, you can uncomment the following line to keep the container running
    # command: tail -f /dev/null
